version: '2.0'
services:

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel-ecommerce-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  #MySQL Service
  db:
    image: mysql:5.7.32
    container_name: laravel-ecommerce-db 
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "db_laravel"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "admin" 
      MYSQL_PASSWORD: "password"
      SERVICE_TAGS: "dev"
      SERVICE_NAME: "mysql"
    volumes:
      - ./mysql/dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/general.log:/var/lib/mysql/general.log
    networks:
      - app-network
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudsigma.com/php
    container_name: laravel-ecommerce-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - app-network     

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
